model:
  _target_: MeshNet
  n_channels: 1
  n_classes: 60

args:
  expdir: "./training"
  logdir: &logdir "./logs"
  verbose: True
  deterministic: False

runner:
  _target_: CustomSupervisedConfigRunner
  input_key: &model_input "images"
  output_key: &model_output "logits"
  target_key: &model_target "targets"

engine:
  _target_: DeviceEngine

loggers:
  console:
    _target_: ConsoleLogger

stages:
  train:
    num_epochs: 30

    loaders: &loaders
      in_csv_train: "./data/dataset_train.csv"
      in_csv_valid: "./data/dataset_valid.csv"
      subvolume_shape: [38, 38, 38]
      volume_shape: [256, 256, 256]
      batch_size: 16
      num_workers: 20
      pin_memory: True

    criterion:
      _target_: CrossEntropyLoss

    optimizer:
      _target_: Adam
      lr: 0.01
      weight_decay: 0.0001

    scheduler:
      _target_: CosineAnnealingWarmRestarts
      T_0: 30
      T_mult: 2
      eta_min: 1e-10

    callbacks: &callbacks
      scheduler:
        _target_: SchedulerCallback
      dice:
        _target_: CustomDiceCallback
        input_key: *model_output
        target_key: *model_target
        metric_key: "dice"
        num_classes: 60
      loss:
        _target_: CriterionCallback
        input_key: *model_output
        target_key: *model_target
        metric_key: &model_loss "loss"
      optimizer:
        _target_: OptimizerCallback
        metric_key: *model_loss
      saver:
        _target_: CheckpointCallback
        logdir: *logdir
